### ISSUE TITLE
Title and headings — Consistency

### ISSUE THREAD

**Issue by JayPanoz** [IDPF/epub-vocabs#1]
Link to section: https://idpf.github.io/epub-vocabs/structure/#h_titles

As a non-native english speaker, I don't get why `subtitle` has “phrasing content descendants of heading content” in its HTML context while `label` and  `ordinal` don't, the text label preceding an ordinal in a component title. 

So and correct me if I'm wrong, are those two inflections meant to be used like this? 

```
<h1>
   <span epub:type="label">Chapter</span> 
   <span epub:type="ordinal">1</span>
</h1>
```

and

```
<figcaption>
  <span epub:type="label">Figure</span> 
  <span epub:type="ordinal">B1</span>
</figcaption>
```

Does the HTML context actually apply to descendants of heading-content, li and figcaption, or am I missing something? I must admit I'm not sure at all when comparing those two drafts to `subtitle`…

[edit] Also, authoring practices/examples would be very warmly welcome (applies to DPUB Aria Roles as well) cos’ sometimes, it’s quite complex for non-native english speakers to make sense of some inflections.

**Comment by mattgarrish** [comment]
Yes, "Phrasing content descendants of" is currently missing from the ordinal and label descriptions. They aren't intended to be used directly on heading, list items or figure caption elements.

**Comment by mattgarrish** [comment]
See also the examples in the edupub vocabulary: http://www.idpf.org/epub/profiles/edu/structure/#h.8py6ho37q2jz

**Comment by JayPanoz** [comment]
OK thanks!

**Comment by mattgarrish** [comment]
I've updated the usage description in the following commit https://github.com/IDPF/epub-vocabs/commit/ddb1626a809392be887ed42fa4e1b3d1b3ac1ff5

I'll close this and add the issue to the main tracker so that the edupub description gets updated when we return to it.
