### ISSUE TITLE
Chapter types in matters.

### ISSUE THREAD

**Issue by jenstroeger** [IDPF/epub-vocabs#8]
It’s probably just a recommendation anyway, but I noticed that [Document partitions](https://idpf.github.io/epub-vocabs/structure/#partitions) lists **frontmatter** which says 

> Preliminary material to the main content of a publication, such as tables of contents, dedications, etc.

Alas, the table of contents is not listed in [Preliminary sections and components](https://idpf.github.io/epub-vocabs/structure/#preliminary) (which I take is a more detailed layout of the frontmatter), and perhaps it should also link to [Document navigation](https://idpf.github.io/epub-vocabs/structure/#navigation) which I I take is a detailed layout of the various tables of contents/figures/… which, in turn, are part of the frontmatter.

Similarly, the **backmatter** definition says:

> Ancillary material occurring after the main content of a publication, such as indices, appendices, etc.

and it seems to me that [Notes and annotations](https://idpf.github.io/epub-vocabs/structure/#notes) lists some backmatter chapters without actually saying so.

I guess what I’m saying is that there’s no clear recommendation which chapter type is considered to belong into which matter; it feels a bit incomplete to me.

**Comment by mattgarrish** [comment]
> Alas, the table of contents is not listed in Preliminary sections and components

It's not that straightforward. If you're French, for example, you'd expect the table of contents to appear in the back matter. Not all the semantics easily fall into specific categories, although the categories themselves are only for general comprehension.

The semantics largely have no effect in reading systems, though, so their primary use is arguably internal data modelling for publishers (with some exceptions like the semantics in the nav doc, of course). You need to determine if the semantics add anything to your processes and how you need to model them to make that happen, in other words. Some people will find the general groupings (front, body and back matter) irrelevant, for example.

**Comment by jenstroeger** [comment]
> If you're French, for example, you'd expect the table of contents to appear in the back matter.

@mattgarrish, yes, the Italians do the same.

> You need to determine if the semantics add anything to your processes and how you need to model them to make that happen, in other words. Some people will find the general groupings (front, body and back matter) irrelevant, for example.

Yes I agree with that, something I keep pondering myself quite a bit when auto-generating e.g. landmarks navs.

Shall I close this issue then?

**Comment by mattgarrish** [comment]
> Yes I agree with that, something I keep pondering myself quite a bit when auto-generating e.g. landmarks navs.

Yes, the landmarks nav is a question that comes up from time to time. In a way, it's terribly conceived as it tries to infer a structure that is actually at the destination of the link, whereas epub:type is supposed to be telling you about the element itself. We probably should have tried to find a way to use "rel" given how few semantics are picked up by reading systems. But that ship has probably sailed, though, as I can't see major changes to the navigation document anymore.

It's still a question that we should try to answer better in the future by looking at the semantics that actually have traction. That's more of a best practice question, though, so is maybe one to raise with the publishing community group.

> Shall I close this issue then?

That's up to you. I'll never tell someone to close an issue unless it's invalid. I'm just offering my perspective that I think it'll be hard to model the semantics any further than general grouping.
